package io.github.rroyoo.mockjdbc.mock.statement;

import io.github.rroyoo.mockjdbc.mock.driver.MockConfig;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

final class StatementQueryHandler {

    private final StatementLifecycleHandler lifecycle;
    private final StatementExecutionStateHandler executionState;
    private final GrpcMockQueryClient client;
    private final GeneratedKeysHandler generatedKeys;
    private final List<String> batchSql = new ArrayList<>();

    StatementQueryHandler(MockConfig mockConfig,
                          StatementLifecycleHandler lifecycle,
                          StatementExecutionStateHandler executionState,
                          GeneratedKeysHandler generatedKeys) {
        this.lifecycle = lifecycle;
        this.executionState = executionState;
        this.generatedKeys = generatedKeys;
        this.client = new GrpcMockQueryClient(mockConfig);
    }

    public ResultSet executeQuery(String sql) throws SQLException {
        lifecycle.assertOpen();
        generatedKeys.clearGeneratedKeys();
        var resultSet = ResultSetFactory.create(client.findResultSet(sql, List.of()));
        executionState.storeResultSet(resultSet);
        return resultSet;
    }

    public boolean execute(String sql) throws SQLException {
        executeQuery(sql);
        return true;
    }

    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        lifecycle.assertOpen();
        var serializedResultSet = client.findResultSet(sql, List.of());
        executionState.storeResultSet(ResultSetFactory.create(serializedResultSet));
        if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS) {
            generatedKeys.storeGeneratedKeys(serializedResultSet);
        } else {
            generatedKeys.clearGeneratedKeys();
        }
        return true;
    }

    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        lifecycle.assertOpen();
        var serializedResultSet = client.findResultSet(sql, List.of());
        executionState.storeResultSet(ResultSetFactory.create(serializedResultSet));
        if (columnIndexes != null && columnIndexes.length > 0) {
            generatedKeys.storeGeneratedKeys(serializedResultSet);
        } else {
            generatedKeys.clearGeneratedKeys();
        }
        return true;
    }

    public boolean execute(String sql, String[] columnNames) throws SQLException {
        lifecycle.assertOpen();
        var serializedResultSet = client.findResultSet(sql, List.of());
        executionState.storeResultSet(ResultSetFactory.create(serializedResultSet));
        if (columnNames != null && columnNames.length > 0) {
            generatedKeys.storeGeneratedKeys(serializedResultSet);
        } else {
            generatedKeys.clearGeneratedKeys();
        }
        return true;
    }

    public int executeUpdate(String sql) throws SQLException {
        lifecycle.assertOpen();
        generatedKeys.clearGeneratedKeys();
        var resultSet = client.findResultSet(sql, List.of());
        var count = resultSet.getRowsCount();
        executionState.storeUpdateCount(count);
        return count;
    }

    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        lifecycle.assertOpen();
        var resultSet = client.findResultSet(sql, List.of());
        var count = resultSet.getRowsCount();
        executionState.storeUpdateCount(count);
        if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS) {
            generatedKeys.storeGeneratedKeys(resultSet);
        } else {
            generatedKeys.clearGeneratedKeys();
        }
        return count;
    }

    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        lifecycle.assertOpen();
        var resultSet = client.findResultSet(sql, List.of());
        var count = resultSet.getRowsCount();
        executionState.storeUpdateCount(count);
        if (columnIndexes != null && columnIndexes.length > 0) {
            generatedKeys.storeGeneratedKeys(resultSet);
        } else {
            generatedKeys.clearGeneratedKeys();
        }
        return count;
    }

    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        lifecycle.assertOpen();
        var resultSet = client.findResultSet(sql, List.of());
        var count = resultSet.getRowsCount();
        executionState.storeUpdateCount(count);
        if (columnNames != null && columnNames.length > 0) {
            generatedKeys.storeGeneratedKeys(resultSet);
        } else {
            generatedKeys.clearGeneratedKeys();
        }
        return count;
    }

    public long executeLargeUpdate(String sql) throws SQLException {
        lifecycle.assertOpen();
        generatedKeys.clearGeneratedKeys();
        var resultSet = client.findResultSet(sql, List.of());
        var count = (long) resultSet.getRowsCount();
        executionState.storeLargeUpdateCount(count);
        return count;
    }

    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        lifecycle.assertOpen();
        var resultSet = client.findResultSet(sql, List.of());
        var count = (long) resultSet.getRowsCount();
        executionState.storeLargeUpdateCount(count);
        if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS) {
            generatedKeys.storeGeneratedKeys(resultSet);
        } else {
            generatedKeys.clearGeneratedKeys();
        }
        return count;
    }

    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        lifecycle.assertOpen();
        var resultSet = client.findResultSet(sql, List.of());
        var count = (long) resultSet.getRowsCount();
        executionState.storeLargeUpdateCount(count);
        if (columnIndexes != null && columnIndexes.length > 0) {
            generatedKeys.storeGeneratedKeys(resultSet);
        } else {
            generatedKeys.clearGeneratedKeys();
        }
        return count;
    }

    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        lifecycle.assertOpen();
        var resultSet = client.findResultSet(sql, List.of());
        var count = (long) resultSet.getRowsCount();
        executionState.storeLargeUpdateCount(count);
        if (columnNames != null && columnNames.length > 0) {
            generatedKeys.storeGeneratedKeys(resultSet);
        } else {
            generatedKeys.clearGeneratedKeys();
        }
        return count;
    }

    public ResultSet getResultSet() throws SQLException {
        lifecycle.assertOpen();
        return executionState.getResultSet();
    }

    public int getUpdateCount() throws SQLException {
        lifecycle.assertOpen();
        return executionState.getUpdateCount();
    }

    public long getLargeUpdateCount() throws SQLException {
        lifecycle.assertOpen();
        return executionState.getLargeUpdateCount();
    }

    public boolean getMoreResults() throws SQLException {
        lifecycle.assertOpen();
        return executionState.getMoreResults();
    }

    public boolean getMoreResults(int current) throws SQLException {
        lifecycle.assertOpen();
        return executionState.getMoreResults(current);
    }

    public void closeOnCompletion() throws SQLException {
        lifecycle.assertOpen();
        executionState.closeOnCompletion();
    }

    public boolean isCloseOnCompletion() throws SQLException {
        lifecycle.assertOpen();
        return executionState.isCloseOnCompletion();
    }

    public ResultSet getGeneratedKeys() throws SQLException {
        lifecycle.assertOpen();
        return generatedKeys.getGeneratedKeys();
    }

    public void addBatch(String sql) throws SQLException {
        lifecycle.assertOpen();
        batchSql.add(sql);
    }

    public void clearBatch() throws SQLException {
        lifecycle.assertOpen();
        batchSql.clear();
    }

    public int[] executeBatch() throws SQLException {
        lifecycle.assertOpen();
        generatedKeys.clearGeneratedKeys();

        var result = new int[batchSql.size()];
        for (int i = 0; i < batchSql.size(); i++) {
            result[i] = client.findResultSet(batchSql.get(i), List.of()).getRowsCount();
        }

        batchSql.clear();
        executionState.storeUpdateCount(-1);
        return result;
    }

    public long[] executeLargeBatch() throws SQLException {
        lifecycle.assertOpen();
        generatedKeys.clearGeneratedKeys();

        var result = new long[batchSql.size()];
        for (int i = 0; i < batchSql.size(); i++) {
            result[i] = client.findResultSet(batchSql.get(i), List.of()).getRowsCount();
        }

        batchSql.clear();
        executionState.storeLargeUpdateCount(-1L);
        return result;
    }
}
