package io.github.rroyoo.mockjdbc.mock.statement;

import io.github.rroyoo.mockjdbc.mock.driver.MockConfig;

import java.io.InputStream;
import java.io.Reader;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLXML;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;

/**
 * Creates mock Statement / PreparedStatement / CallableStatement instances backed by JDK dynamic proxies.
 *
 * <p>JDK proxy classes are cached by the runtime for a given (ClassLoader, interfaces[]) tuple,
 * so no bytecode is generated after the first call per statement type — eliminating the
 * per-instance ByteBuddy class-generation cost.
 */
public final class StatementFactory {

    private final MockConfig mockConfig;

    public StatementFactory(MockConfig mockConfig) {
        if (mockConfig == null) {
            throw new IllegalArgumentException("MockConfig cannot be null");
        }
        this.mockConfig = mockConfig;
    }

    // ── Public creation API ────────────────────────────────────────────────

    public Statement createStatement() throws SQLException { return buildStatement(); }
    public Statement createStatement(int ignored1, int ignored2) throws SQLException { return buildStatement(); }
    public Statement createStatement(int ignored1, int ignored2, int ignored3) throws SQLException { return buildStatement(); }

    public PreparedStatement prepareStatement(String sql) throws SQLException { return buildPreparedStatement(sql, false); }
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException { return buildPreparedStatement(sql, autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS); }
    public PreparedStatement prepareStatement(String sql, int ignored1, int ignored2) throws SQLException { return buildPreparedStatement(sql, false); }
    public PreparedStatement prepareStatement(String sql, int ignored1, int ignored2, int ignored3) throws SQLException { return buildPreparedStatement(sql, false); }
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException { return buildPreparedStatement(sql, columnIndexes != null && columnIndexes.length > 0); }
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException { return buildPreparedStatement(sql, columnNames != null && columnNames.length > 0); }

    public CallableStatement prepareCall(String sql) throws SQLException { return buildCallableStatement(sql); }
    public CallableStatement prepareCall(String sql, int ignored1, int ignored2) throws SQLException { return buildCallableStatement(sql); }
    public CallableStatement prepareCall(String sql, int ignored1, int ignored2, int ignored3) throws SQLException { return buildCallableStatement(sql); }

    // ── Builders ───────────────────────────────────────────────────────────

    private Statement buildStatement() throws SQLException {
        try {
            var lifecycle      = new StatementLifecycleHandler();
            var warnings       = new StatementWarningsHandler();
            var config         = new StatementConfigHandler();
            var executionState = new StatementExecutionStateHandler();
            var generatedKeys  = new GeneratedKeysHandler();
            var misc           = new StatementMiscHandler(mockConfig, lifecycle);
            var query          = new StatementQueryHandler(mockConfig, lifecycle, executionState, generatedKeys);

            return (Statement) Proxy.newProxyInstance(
                    StatementFactory.class.getClassLoader(),
                    new Class<?>[]{ Statement.class },
                    new StatementInvocationHandler(lifecycle, warnings, config, misc, query)
            );
        } catch (Exception e) {
            throw new SQLException("Failed to create mock Statement", e);
        }
    }

    private PreparedStatement buildPreparedStatement(String sql, boolean returnGeneratedKeys) throws SQLException {
        try {
            var lifecycle      = new StatementLifecycleHandler();
            var warnings       = new StatementWarningsHandler();
            var config         = new StatementConfigHandler();
            var executionState = new StatementExecutionStateHandler();
            var generatedKeys  = new GeneratedKeysHandler();
            var misc           = new StatementMiscHandler(mockConfig, lifecycle);
            var prepared       = new PreparedStatementQueryHandler(mockConfig, lifecycle, executionState, generatedKeys, returnGeneratedKeys, sql);

            return (PreparedStatement) Proxy.newProxyInstance(
                    StatementFactory.class.getClassLoader(),
                    new Class<?>[]{ PreparedStatement.class },
                    new PreparedStatementInvocationHandler(lifecycle, warnings, config, misc, prepared)
            );
        } catch (Exception e) {
            throw new SQLException("Failed to create mock PreparedStatement", e);
        }
    }

    private CallableStatement buildCallableStatement(String sql) throws SQLException {
        try {
            var lifecycle      = new StatementLifecycleHandler();
            var warnings       = new StatementWarningsHandler();
            var config         = new StatementConfigHandler();
            var executionState = new StatementExecutionStateHandler();
            var generatedKeys  = new GeneratedKeysHandler();
            var misc           = new StatementMiscHandler(mockConfig, lifecycle);
            var callable       = new PreparedStatementQueryHandler(mockConfig, lifecycle, executionState, generatedKeys, false, sql);
            var outParams      = new CallableStatementOutParamHandler(lifecycle);

            return (CallableStatement) Proxy.newProxyInstance(
                    StatementFactory.class.getClassLoader(),
                    new Class<?>[]{ CallableStatement.class },
                    new CallableStatementInvocationHandler(lifecycle, warnings, config, misc, callable, outParams)
            );
        } catch (Exception e) {
            throw new SQLException("Failed to create mock CallableStatement", e);
        }
    }

    // ── Dispatch infrastructure ────────────────────────────────────────────

    @FunctionalInterface
    interface MethodInvoker {
        Object invoke(Object[] args) throws Exception;
    }

    /**
     * Base InvocationHandler for all statement types. Contains the shared Statement methods.
     */
    private static class StatementInvocationHandler implements InvocationHandler {

        protected final Map<Method, MethodInvoker> dispatch;

        StatementInvocationHandler(
                StatementLifecycleHandler lifecycle,
                StatementWarningsHandler warnings,
                StatementConfigHandler config,
                StatementMiscHandler misc,
                StatementQueryHandler query) throws NoSuchMethodException {
            dispatch = new HashMap<>();
            addSharedMethods(dispatch, lifecycle, warnings, config, misc, query);
        }

        // For subclasses that use a different queryHandler type (no String-variant methods)
        StatementInvocationHandler(Map<Method, MethodInvoker> dispatch) {
            this.dispatch = dispatch;
        }

        @Override
        public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
            var name = method.getName();
            if ("equals".equals(name))   return proxy == (args != null ? args[0] : null);
            if ("hashCode".equals(name)) return System.identityHashCode(proxy);
            if ("toString".equals(name)) return "MockStatement";

            var invoker = dispatch.get(method);
            if (invoker != null) {
                return invoker.invoke(args);
            }

            var returnType = method.getReturnType();
            if (returnType == void.class || returnType == Void.class) return null;
            if (returnType == boolean.class) return false;
            if (returnType == int.class)     return 0;
            if (returnType == long.class)    return 0L;
            return null;
        }

        /**
         * Populates the dispatch map with methods common to all statement types.
         * String-variant execute methods are only added when {@code query} is not null.
         */
        protected static void addSharedMethods(Map<Method, MethodInvoker> d,
                                               StatementLifecycleHandler lifecycle,
                                               StatementWarningsHandler warnings,
                                               StatementConfigHandler config,
                                               StatementMiscHandler misc,
                                               StatementQueryHandler query) throws NoSuchMethodException {
            var s = Statement.class;

            // ── lifecycle ────────────────────────────────────────────────────
            d.put(s.getMethod("close"),    args -> { lifecycle.close(); return null; });
            d.put(s.getMethod("isClosed"), args -> lifecycle.isClosed());

            // ── batch / result state (shared by all) ─────────────────────────
            d.put(s.getMethod("getResultSet"),         args -> query.getResultSet());
            d.put(s.getMethod("getUpdateCount"),        args -> query.getUpdateCount());
            d.put(s.getMethod("getLargeUpdateCount"),   args -> query.getLargeUpdateCount());
            d.put(s.getMethod("getMoreResults"),        args -> query.getMoreResults());
            d.put(s.getMethod("getMoreResults", int.class), args -> query.getMoreResults((int) args[0]));
            d.put(s.getMethod("getGeneratedKeys"),      args -> query.getGeneratedKeys());
            d.put(s.getMethod("clearBatch"),            args -> { query.clearBatch(); return null; });
            d.put(s.getMethod("executeBatch"),          args -> query.executeBatch());
            d.put(s.getMethod("executeLargeBatch"),     args -> query.executeLargeBatch());
            d.put(s.getMethod("closeOnCompletion"),     args -> { query.closeOnCompletion(); return null; });
            d.put(s.getMethod("isCloseOnCompletion"),   args -> query.isCloseOnCompletion());

            // ── String-variant execute methods (Statement only) ──────────────
            d.put(s.getMethod("executeQuery", String.class),                  args -> query.executeQuery((String) args[0]));
            d.put(s.getMethod("execute", String.class),                       args -> query.execute((String) args[0]));
            d.put(s.getMethod("execute", String.class, int.class),            args -> query.execute((String) args[0], (int) args[1]));
            d.put(s.getMethod("execute", String.class, int[].class),          args -> query.execute((String) args[0], (int[]) args[1]));
            d.put(s.getMethod("execute", String.class, String[].class),       args -> query.execute((String) args[0], (String[]) args[1]));
            d.put(s.getMethod("executeUpdate", String.class),                 args -> query.executeUpdate((String) args[0]));
            d.put(s.getMethod("executeUpdate", String.class, int.class),      args -> query.executeUpdate((String) args[0], (int) args[1]));
            d.put(s.getMethod("executeUpdate", String.class, int[].class),    args -> query.executeUpdate((String) args[0], (int[]) args[1]));
            d.put(s.getMethod("executeUpdate", String.class, String[].class), args -> query.executeUpdate((String) args[0], (String[]) args[1]));
            d.put(s.getMethod("executeLargeUpdate", String.class),            args -> query.executeLargeUpdate((String) args[0]));
            d.put(s.getMethod("executeLargeUpdate", String.class, int.class), args -> query.executeLargeUpdate((String) args[0], (int) args[1]));
            d.put(s.getMethod("executeLargeUpdate", String.class, int[].class), args -> query.executeLargeUpdate((String) args[0], (int[]) args[1]));
            d.put(s.getMethod("executeLargeUpdate", String.class, String[].class), args -> query.executeLargeUpdate((String) args[0], (String[]) args[1]));
            d.put(s.getMethod("addBatch", String.class),                      args -> { query.addBatch((String) args[0]); return null; });

            // ── misc ─────────────────────────────────────────────────────────
            d.put(s.getMethod("setPoolable", boolean.class),      args -> { misc.setPoolable((boolean) args[0]); return null; });
            d.put(s.getMethod("isPoolable"),                      args -> misc.isPoolable());
            d.put(s.getMethod("setEscapeProcessing", boolean.class), args -> { misc.setEscapeProcessing((boolean) args[0]); return null; });
            d.put(s.getMethod("setCursorName", String.class),     args -> { misc.setCursorName((String) args[0]); return null; });
            d.put(s.getMethod("cancel"),                          args -> { misc.cancel(); return null; });
            d.put(s.getMethod("getConnection"),                   args -> misc.getConnection());

            // ── warnings ─────────────────────────────────────────────────────
            d.put(s.getMethod("getWarnings"),   args -> warnings.getWarnings());
            d.put(s.getMethod("clearWarnings"), args -> { warnings.clearWarnings(); return null; });

            // ── config ───────────────────────────────────────────────────────
            d.put(s.getMethod("setMaxRows", int.class),           args -> { config.setMaxRows((int) args[0]); return null; });
            d.put(s.getMethod("getMaxRows"),                      args -> config.getMaxRows());
            d.put(s.getMethod("setLargeMaxRows", long.class),     args -> { config.setLargeMaxRows((long) args[0]); return null; });
            d.put(s.getMethod("getLargeMaxRows"),                 args -> config.getLargeMaxRows());
            d.put(s.getMethod("setQueryTimeout", int.class),      args -> { config.setQueryTimeout((int) args[0]); return null; });
            d.put(s.getMethod("getQueryTimeout"),                 args -> config.getQueryTimeout());
            d.put(s.getMethod("setFetchSize", int.class),         args -> { config.setFetchSize((int) args[0]); return null; });
            d.put(s.getMethod("getFetchSize"),                    args -> config.getFetchSize());
            d.put(s.getMethod("setFetchDirection", int.class),    args -> { config.setFetchDirection((int) args[0]); return null; });
            d.put(s.getMethod("getFetchDirection"),               args -> config.getFetchDirection());
            d.put(s.getMethod("getResultSetType"),                args -> config.getResultSetType());
            d.put(s.getMethod("getResultSetConcurrency"),         args -> config.getResultSetConcurrency());
            d.put(s.getMethod("getResultSetHoldability"),         args -> config.getResultSetHoldability());
            d.put(s.getMethod("setMaxFieldSize", int.class),      args -> null);
            d.put(s.getMethod("getMaxFieldSize"),                 args -> 0);

            // ── unwrap ───────────────────────────────────────────────────────
            d.put(s.getMethod("isWrapperFor", Class.class), args -> false);
            d.put(s.getMethod("unwrap", Class.class),       args -> { throw new SQLException("Not a wrapper for " + args[0]); });
        }
    }

    private static final class PreparedStatementInvocationHandler extends StatementInvocationHandler {

        PreparedStatementInvocationHandler(
                StatementLifecycleHandler lifecycle,
                StatementWarningsHandler warnings,
                StatementConfigHandler config,
                StatementMiscHandler misc,
                PreparedStatementQueryHandler prepared) throws NoSuchMethodException {
            super(buildPreparedDispatch(lifecycle, warnings, config, misc, prepared));
        }

        private static Map<Method, MethodInvoker> buildPreparedDispatch(
                StatementLifecycleHandler lifecycle,
                StatementWarningsHandler warnings,
                StatementConfigHandler config,
                StatementMiscHandler misc,
                PreparedStatementQueryHandler prepared) throws NoSuchMethodException {

            var d = new HashMap<Method, MethodInvoker>();

            // Reuse the Statement-level shared methods via a dummy StatementQueryHandler adapter.
            // For PreparedStatement we need an adapter that exposes getResultSet, etc.
            addPreparedSharedMethods(d, lifecycle, warnings, config, misc, prepared);
            addPreparedParameterMethods(d, prepared);
            return d;
        }

        private static void addPreparedSharedMethods(
                Map<Method, MethodInvoker> d,
                StatementLifecycleHandler lifecycle,
                StatementWarningsHandler warnings,
                StatementConfigHandler config,
                StatementMiscHandler misc,
                PreparedStatementQueryHandler prepared) throws NoSuchMethodException {

            var s = Statement.class;
            var ps = PreparedStatement.class;

            // ── lifecycle ────────────────────────────────────────────────────
            d.put(s.getMethod("close"),    args -> { lifecycle.close(); return null; });
            d.put(s.getMethod("isClosed"), args -> lifecycle.isClosed());

            // ── no-arg execute methods (PreparedStatement-specific) ───────────
            d.put(ps.getMethod("executeQuery"),        args -> prepared.executeQuery());
            d.put(ps.getMethod("execute"),             args -> prepared.execute());
            d.put(ps.getMethod("executeUpdate"),       args -> prepared.executeUpdate());
            d.put(ps.getMethod("executeLargeUpdate"),  args -> prepared.executeLargeUpdate());

            // ── batch / result state ─────────────────────────────────────────
            d.put(s.getMethod("getResultSet"),         args -> prepared.getResultSet());
            d.put(s.getMethod("getUpdateCount"),       args -> prepared.getUpdateCount());
            d.put(s.getMethod("getLargeUpdateCount"),  args -> prepared.getLargeUpdateCount());
            d.put(s.getMethod("getMoreResults"),       args -> prepared.getMoreResults());
            d.put(s.getMethod("getMoreResults", int.class), args -> prepared.getMoreResults((int) args[0]));
            d.put(s.getMethod("getGeneratedKeys"),     args -> prepared.getGeneratedKeys());
            d.put(ps.getMethod("addBatch"),            args -> { prepared.addBatch(); return null; });
            d.put(s.getMethod("clearBatch"),           args -> { prepared.clearBatch(); return null; });
            d.put(s.getMethod("executeBatch"),         args -> prepared.executeBatch());
            d.put(s.getMethod("executeLargeBatch"),    args -> prepared.executeLargeBatch());
            d.put(s.getMethod("closeOnCompletion"),    args -> { prepared.closeOnCompletion(); return null; });
            d.put(s.getMethod("isCloseOnCompletion"),  args -> prepared.isCloseOnCompletion());

            // ── metadata ─────────────────────────────────────────────────────
            d.put(ps.getMethod("getParameterMetaData"), args -> prepared.getParameterMetaData());
            d.put(ps.getMethod("getMetaData"),          args -> prepared.getMetaData());

            // ── misc ─────────────────────────────────────────────────────────
            d.put(s.getMethod("setPoolable", boolean.class),         args -> { misc.setPoolable((boolean) args[0]); return null; });
            d.put(s.getMethod("isPoolable"),                         args -> misc.isPoolable());
            d.put(s.getMethod("setEscapeProcessing", boolean.class), args -> { misc.setEscapeProcessing((boolean) args[0]); return null; });
            d.put(s.getMethod("setCursorName", String.class),        args -> { misc.setCursorName((String) args[0]); return null; });
            d.put(s.getMethod("cancel"),                             args -> { misc.cancel(); return null; });
            d.put(s.getMethod("getConnection"),                      args -> misc.getConnection());

            // ── warnings ─────────────────────────────────────────────────────
            d.put(s.getMethod("getWarnings"),   args -> warnings.getWarnings());
            d.put(s.getMethod("clearWarnings"), args -> { warnings.clearWarnings(); return null; });

            // ── config ───────────────────────────────────────────────────────
            d.put(s.getMethod("setMaxRows", int.class),       args -> { config.setMaxRows((int) args[0]); return null; });
            d.put(s.getMethod("getMaxRows"),                  args -> config.getMaxRows());
            d.put(s.getMethod("setLargeMaxRows", long.class), args -> { config.setLargeMaxRows((long) args[0]); return null; });
            d.put(s.getMethod("getLargeMaxRows"),             args -> config.getLargeMaxRows());
            d.put(s.getMethod("setQueryTimeout", int.class),  args -> { config.setQueryTimeout((int) args[0]); return null; });
            d.put(s.getMethod("getQueryTimeout"),             args -> config.getQueryTimeout());
            d.put(s.getMethod("setFetchSize", int.class),     args -> { config.setFetchSize((int) args[0]); return null; });
            d.put(s.getMethod("getFetchSize"),                args -> config.getFetchSize());
            d.put(s.getMethod("setFetchDirection", int.class), args -> { config.setFetchDirection((int) args[0]); return null; });
            d.put(s.getMethod("getFetchDirection"),           args -> config.getFetchDirection());
            d.put(s.getMethod("getResultSetType"),            args -> config.getResultSetType());
            d.put(s.getMethod("getResultSetConcurrency"),     args -> config.getResultSetConcurrency());
            d.put(s.getMethod("getResultSetHoldability"),     args -> config.getResultSetHoldability());
            d.put(s.getMethod("setMaxFieldSize", int.class),  args -> null);
            d.put(s.getMethod("getMaxFieldSize"),             args -> 0);

            // ── unwrap ───────────────────────────────────────────────────────
            d.put(s.getMethod("isWrapperFor", Class.class), args -> false);
            d.put(s.getMethod("unwrap", Class.class), args -> { throw new SQLException("Not a wrapper for " + args[0]); });

            // ── clear parameters ─────────────────────────────────────────────
            d.put(ps.getMethod("clearParameters"), args -> { prepared.clearParameters(); return null; });
        }

        private static void addPreparedParameterMethods(
                Map<Method, MethodInvoker> d,
                PreparedStatementQueryHandler p) throws NoSuchMethodException {
            var ps = PreparedStatement.class;

            d.put(ps.getMethod("setString",       int.class, String.class),      args -> { p.setString((int) args[0], (String) args[1]); return null; });
            d.put(ps.getMethod("setInt",          int.class, int.class),          args -> { p.setInt((int) args[0], (int) args[1]); return null; });
            d.put(ps.getMethod("setLong",         int.class, long.class),         args -> { p.setLong((int) args[0], (long) args[1]); return null; });
            d.put(ps.getMethod("setBoolean",      int.class, boolean.class),      args -> { p.setBoolean((int) args[0], (boolean) args[1]); return null; });
            d.put(ps.getMethod("setDouble",       int.class, double.class),       args -> { p.setDouble((int) args[0], (double) args[1]); return null; });
            d.put(ps.getMethod("setFloat",        int.class, float.class),        args -> { p.setFloat((int) args[0], (float) args[1]); return null; });
            d.put(ps.getMethod("setShort",        int.class, short.class),        args -> { p.setShort((int) args[0], (short) args[1]); return null; });
            d.put(ps.getMethod("setByte",         int.class, byte.class),         args -> { p.setByte((int) args[0], (byte) args[1]); return null; });
            d.put(ps.getMethod("setBytes",        int.class, byte[].class),       args -> { p.setBytes((int) args[0], (byte[]) args[1]); return null; });
            d.put(ps.getMethod("setBigDecimal",   int.class, BigDecimal.class),   args -> { p.setBigDecimal((int) args[0], (BigDecimal) args[1]); return null; });
            d.put(ps.getMethod("setDate",         int.class, Date.class),         args -> { p.setDate((int) args[0], (Date) args[1]); return null; });
            d.put(ps.getMethod("setDate",         int.class, Date.class, Calendar.class), args -> { p.setDate((int) args[0], (Date) args[1], (Calendar) args[2]); return null; });
            d.put(ps.getMethod("setTime",         int.class, Time.class),         args -> { p.setTime((int) args[0], (Time) args[1]); return null; });
            d.put(ps.getMethod("setTime",         int.class, Time.class, Calendar.class), args -> { p.setTime((int) args[0], (Time) args[1], (Calendar) args[2]); return null; });
            d.put(ps.getMethod("setTimestamp",    int.class, Timestamp.class),    args -> { p.setTimestamp((int) args[0], (Timestamp) args[1]); return null; });
            d.put(ps.getMethod("setTimestamp",    int.class, Timestamp.class, Calendar.class), args -> { p.setTimestamp((int) args[0], (Timestamp) args[1], (Calendar) args[2]); return null; });
            d.put(ps.getMethod("setObject",       int.class, Object.class),       args -> { p.setObject((int) args[0], args[1]); return null; });
            d.put(ps.getMethod("setObject",       int.class, Object.class, int.class), args -> { p.setObject((int) args[0], args[1], (int) args[2]); return null; });
            d.put(ps.getMethod("setObject",       int.class, Object.class, int.class, int.class), args -> { p.setObject((int) args[0], args[1], (int) args[2], (int) args[3]); return null; });
            d.put(ps.getMethod("setNull",         int.class, int.class),          args -> { p.setNull((int) args[0], (int) args[1]); return null; });
            d.put(ps.getMethod("setNull",         int.class, int.class, String.class), args -> { p.setNull((int) args[0], (int) args[1], (String) args[2]); return null; });
            d.put(ps.getMethod("setURL",          int.class, URL.class),          args -> { p.setURL((int) args[0], (URL) args[1]); return null; });
            d.put(ps.getMethod("setRowId",        int.class, RowId.class),        args -> { p.setRowId((int) args[0], (RowId) args[1]); return null; });
            d.put(ps.getMethod("setSQLXML",       int.class, SQLXML.class),       args -> { p.setSQLXML((int) args[0], (SQLXML) args[1]); return null; });
            d.put(ps.getMethod("setNString",      int.class, String.class),       args -> { p.setNString((int) args[0], (String) args[1]); return null; });
            d.put(ps.getMethod("setBlob",         int.class, Blob.class),         args -> { p.setBlob((int) args[0], (Blob) args[1]); return null; });
            d.put(ps.getMethod("setBlob",         int.class, InputStream.class),  args -> { p.setBlob((int) args[0], (InputStream) args[1]); return null; });
            d.put(ps.getMethod("setBlob",         int.class, InputStream.class, long.class), args -> { p.setBlob((int) args[0], (InputStream) args[1], (long) args[2]); return null; });
            d.put(ps.getMethod("setClob",         int.class, Clob.class),         args -> { p.setClob((int) args[0], (Clob) args[1]); return null; });
            d.put(ps.getMethod("setClob",         int.class, Reader.class),       args -> { p.setClob((int) args[0], (Reader) args[1]); return null; });
            d.put(ps.getMethod("setClob",         int.class, Reader.class, long.class), args -> { p.setClob((int) args[0], (Reader) args[1], (long) args[2]); return null; });
            d.put(ps.getMethod("setNClob",        int.class, NClob.class),        args -> { p.setNClob((int) args[0], (NClob) args[1]); return null; });
            d.put(ps.getMethod("setNClob",        int.class, Reader.class),       args -> { p.setNClob((int) args[0], (Reader) args[1]); return null; });
            d.put(ps.getMethod("setNClob",        int.class, Reader.class, long.class), args -> { p.setNClob((int) args[0], (Reader) args[1], (long) args[2]); return null; });
            d.put(ps.getMethod("setArray",        int.class, Array.class),        args -> { p.setArray((int) args[0], (Array) args[1]); return null; });
            d.put(ps.getMethod("setRef",          int.class, Ref.class),          args -> { p.setRef((int) args[0], (Ref) args[1]); return null; });
            d.put(ps.getMethod("setBinaryStream",    int.class, InputStream.class),              args -> { p.setBinaryStream((int) args[0], (InputStream) args[1]); return null; });
            d.put(ps.getMethod("setBinaryStream",    int.class, InputStream.class, int.class),   args -> { p.setBinaryStream((int) args[0], (InputStream) args[1], (int) args[2]); return null; });
            d.put(ps.getMethod("setBinaryStream",    int.class, InputStream.class, long.class),  args -> { p.setBinaryStream((int) args[0], (InputStream) args[1], (long) args[2]); return null; });
            d.put(ps.getMethod("setCharacterStream", int.class, Reader.class),                   args -> { p.setCharacterStream((int) args[0], (Reader) args[1]); return null; });
            d.put(ps.getMethod("setCharacterStream", int.class, Reader.class, int.class),        args -> { p.setCharacterStream((int) args[0], (Reader) args[1], (int) args[2]); return null; });
            d.put(ps.getMethod("setCharacterStream", int.class, Reader.class, long.class),       args -> { p.setCharacterStream((int) args[0], (Reader) args[1], (long) args[2]); return null; });
            d.put(ps.getMethod("setNCharacterStream", int.class, Reader.class),                  args -> { p.setNCharacterStream((int) args[0], (Reader) args[1]); return null; });
            d.put(ps.getMethod("setNCharacterStream", int.class, Reader.class, long.class),      args -> { p.setNCharacterStream((int) args[0], (Reader) args[1], (long) args[2]); return null; });
            d.put(ps.getMethod("setAsciiStream",     int.class, InputStream.class),              args -> { p.setAsciiStream((int) args[0], (InputStream) args[1]); return null; });
            d.put(ps.getMethod("setAsciiStream",     int.class, InputStream.class, int.class),   args -> { p.setAsciiStream((int) args[0], (InputStream) args[1], (int) args[2]); return null; });
            d.put(ps.getMethod("setAsciiStream",     int.class, InputStream.class, long.class),  args -> { p.setAsciiStream((int) args[0], (InputStream) args[1], (long) args[2]); return null; });
            d.put(ps.getMethod("setUnicodeStream",   int.class, InputStream.class, int.class),   args -> { p.setUnicodeStream((int) args[0], (InputStream) args[1], (int) args[2]); return null; });
        }
    }

    private static final class CallableStatementInvocationHandler extends StatementInvocationHandler {

        CallableStatementInvocationHandler(
                StatementLifecycleHandler lifecycle,
                StatementWarningsHandler warnings,
                StatementConfigHandler config,
                StatementMiscHandler misc,
                PreparedStatementQueryHandler callable,
                CallableStatementOutParamHandler outParams) throws NoSuchMethodException {
            super(buildCallableDispatch(lifecycle, warnings, config, misc, callable, outParams));
        }

        private static Map<Method, MethodInvoker> buildCallableDispatch(
                StatementLifecycleHandler lifecycle,
                StatementWarningsHandler warnings,
                StatementConfigHandler config,
                StatementMiscHandler misc,
                PreparedStatementQueryHandler callable,
                CallableStatementOutParamHandler outParams) throws NoSuchMethodException {

            var d = new HashMap<Method, MethodInvoker>();
            PreparedStatementInvocationHandler.addPreparedSharedMethods(d, lifecycle, warnings, config, misc, callable);
            PreparedStatementInvocationHandler.addPreparedParameterMethods(d, callable);
            addCallableOutMethods(d, outParams);
            return d;
        }

        private static void addCallableOutMethods(
                Map<Method, MethodInvoker> d,
                CallableStatementOutParamHandler o) throws NoSuchMethodException {
            var cs = CallableStatement.class;

            // registerOutParameter
            d.put(cs.getMethod("registerOutParameter", int.class, int.class),                    args -> { o.registerOutParameter((int) args[0], (int) args[1]); return null; });
            d.put(cs.getMethod("registerOutParameter", int.class, int.class, int.class),         args -> { o.registerOutParameter((int) args[0], (int) args[1], (int) args[2]); return null; });
            d.put(cs.getMethod("registerOutParameter", int.class, int.class, String.class),      args -> { o.registerOutParameter((int) args[0], (int) args[1], (String) args[2]); return null; });
            d.put(cs.getMethod("registerOutParameter", String.class, int.class),                 args -> { o.registerOutParameter((String) args[0], (int) args[1]); return null; });
            d.put(cs.getMethod("registerOutParameter", String.class, int.class, int.class),      args -> { o.registerOutParameter((String) args[0], (int) args[1], (int) args[2]); return null; });
            d.put(cs.getMethod("registerOutParameter", String.class, int.class, String.class),   args -> { o.registerOutParameter((String) args[0], (int) args[1], (String) args[2]); return null; });
            d.put(cs.getMethod("wasNull"), args -> o.wasNull());

            // index-based getters
            d.put(cs.getMethod("getString",    int.class),                    args -> o.getString((int) args[0]));
            d.put(cs.getMethod("getBoolean",   int.class),                    args -> o.getBoolean((int) args[0]));
            d.put(cs.getMethod("getByte",      int.class),                    args -> o.getByte((int) args[0]));
            d.put(cs.getMethod("getShort",     int.class),                    args -> o.getShort((int) args[0]));
            d.put(cs.getMethod("getInt",       int.class),                    args -> o.getInt((int) args[0]));
            d.put(cs.getMethod("getLong",      int.class),                    args -> o.getLong((int) args[0]));
            d.put(cs.getMethod("getFloat",     int.class),                    args -> o.getFloat((int) args[0]));
            d.put(cs.getMethod("getDouble",    int.class),                    args -> o.getDouble((int) args[0]));
            d.put(cs.getMethod("getBytes",     int.class),                    args -> o.getBytes((int) args[0]));
            d.put(cs.getMethod("getBigDecimal", int.class),                   args -> o.getBigDecimal((int) args[0]));
            d.put(cs.getMethod("getObject",    int.class),                    args -> o.getObject((int) args[0]));
            d.put(cs.getMethod("getObject",    int.class, Class.class),       args -> o.getObject((int) args[0], (Class<?>) args[1]));
            d.put(cs.getMethod("getDate",      int.class),                    args -> o.getDate((int) args[0]));
            d.put(cs.getMethod("getDate",      int.class, Calendar.class),    args -> o.getDate((int) args[0], (Calendar) args[1]));
            d.put(cs.getMethod("getTime",      int.class),                    args -> o.getTime((int) args[0]));
            d.put(cs.getMethod("getTime",      int.class, Calendar.class),    args -> o.getTime((int) args[0], (Calendar) args[1]));
            d.put(cs.getMethod("getTimestamp", int.class),                    args -> o.getTimestamp((int) args[0]));
            d.put(cs.getMethod("getTimestamp", int.class, Calendar.class),    args -> o.getTimestamp((int) args[0], (Calendar) args[1]));

            // name-based getters
            d.put(cs.getMethod("getString",    String.class),                 args -> o.getString((String) args[0]));
            d.put(cs.getMethod("getBoolean",   String.class),                 args -> o.getBoolean((String) args[0]));
            d.put(cs.getMethod("getByte",      String.class),                 args -> o.getByte((String) args[0]));
            d.put(cs.getMethod("getShort",     String.class),                 args -> o.getShort((String) args[0]));
            d.put(cs.getMethod("getInt",       String.class),                 args -> o.getInt((String) args[0]));
            d.put(cs.getMethod("getLong",      String.class),                 args -> o.getLong((String) args[0]));
            d.put(cs.getMethod("getFloat",     String.class),                 args -> o.getFloat((String) args[0]));
            d.put(cs.getMethod("getDouble",    String.class),                 args -> o.getDouble((String) args[0]));
            d.put(cs.getMethod("getBytes",     String.class),                 args -> o.getBytes((String) args[0]));
            d.put(cs.getMethod("getBigDecimal", String.class),                args -> o.getBigDecimal((String) args[0]));
            d.put(cs.getMethod("getObject",    String.class),                 args -> o.getObject((String) args[0]));
            d.put(cs.getMethod("getObject",    String.class, Class.class),    args -> o.getObject((String) args[0], (Class<?>) args[1]));
            d.put(cs.getMethod("getDate",      String.class),                 args -> o.getDate((String) args[0]));
            d.put(cs.getMethod("getDate",      String.class, Calendar.class), args -> o.getDate((String) args[0], (Calendar) args[1]));
            d.put(cs.getMethod("getTime",      String.class),                 args -> o.getTime((String) args[0]));
            d.put(cs.getMethod("getTime",      String.class, Calendar.class), args -> o.getTime((String) args[0], (Calendar) args[1]));
            d.put(cs.getMethod("getTimestamp", String.class),                 args -> o.getTimestamp((String) args[0]));
            d.put(cs.getMethod("getTimestamp", String.class, Calendar.class), args -> o.getTimestamp((String) args[0], (Calendar) args[1]));
        }
    }
}
