package io.github.rroyoo.mockjdbc.mock.statement;

import io.github.rroyoo.mockjdbc.mock.driver.MockConfig;
import net.bytebuddy.ByteBuddy;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.implementation.MethodCall;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.concurrent.atomic.AtomicLong;

import static net.bytebuddy.matcher.ElementMatchers.named;
import static net.bytebuddy.matcher.ElementMatchers.takesArguments;
import static net.bytebuddy.matcher.ElementMatchers.takesNoArguments;

public final class StatementFactory {

    private static final AtomicLong STATEMENT_SEQUENCE = new AtomicLong(0L);
    private static final AtomicLong PREPARED_STATEMENT_SEQUENCE = new AtomicLong(0L);
    private static final AtomicLong CALLABLE_STATEMENT_SEQUENCE = new AtomicLong(0L);

    private final MockConfig mockConfig;

    public StatementFactory(MockConfig mockConfig) {
        if (mockConfig == null) {
            throw new IllegalArgumentException("MockConfig cannot be null");
        }
        this.mockConfig = mockConfig;
    }

    public Statement createStatement() throws SQLException {
        return buildStatement();
    }

    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return buildStatement();
    }

    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return buildStatement();
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return buildPreparedStatement(sql, false);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return buildPreparedStatement(sql, autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS);
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return buildPreparedStatement(sql, false);
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return buildPreparedStatement(sql, false);
    }

    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return buildPreparedStatement(sql, columnIndexes != null && columnIndexes.length > 0);
    }

    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return buildPreparedStatement(sql, columnNames != null && columnNames.length > 0);
    }

    public CallableStatement prepareCall(String sql) throws SQLException {
        return buildCallableStatement(sql);
    }

    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return buildCallableStatement(sql);
    }

    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return buildCallableStatement(sql);
    }

    private Statement buildStatement() throws SQLException {
        try {
            var lifecycle = new StatementLifecycleHandler();
            var warnings = new StatementWarningsHandler();
            var config = new StatementConfigHandler();
            var executionState = new StatementExecutionStateHandler();
            var generatedKeys = new GeneratedKeysHandler();
            var misc = new StatementMiscHandler(mockConfig, lifecycle);
            var query = new StatementQueryHandler(mockConfig, lifecycle, executionState, generatedKeys);

            var typeName = StatementFactory.class.getPackageName() + ".MockStatement$" + STATEMENT_SEQUENCE.incrementAndGet();

            try (var unloaded = new ByteBuddy()
                    .subclass(Statement.class)
                    .name(typeName)
                    .method(named("close").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("close")).on(lifecycle))
                    .method(named("isClosed").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("isClosed")).on(lifecycle))
                    .method(named("setPoolable").and(takesArguments(boolean.class)))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("setPoolable", boolean.class)).on(misc).withAllArguments())
                    .method(named("isPoolable").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("isPoolable")).on(misc))
                    .method(named("setEscapeProcessing").and(takesArguments(boolean.class)))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("setEscapeProcessing", boolean.class)).on(misc).withAllArguments())
                    .method(named("setCursorName").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("setCursorName", String.class)).on(misc).withAllArguments())
                    .method(named("cancel").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("cancel")).on(misc))
                    .method(named("getConnection").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("getConnection")).on(misc))
                    .method(named("getWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("getWarnings")).on(warnings))
                    .method(named("clearWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("clearWarnings")).on(warnings))
                    .method(named("setMaxRows").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setMaxRows", int.class)).on(config).withAllArguments())
                    .method(named("getMaxRows").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getMaxRows")).on(config))
                    .method(named("setLargeMaxRows").and(takesArguments(long.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setLargeMaxRows", long.class)).on(config).withAllArguments())
                    .method(named("getLargeMaxRows").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getLargeMaxRows")).on(config))
                    .method(named("setQueryTimeout").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setQueryTimeout", int.class)).on(config).withAllArguments())
                    .method(named("getQueryTimeout").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getQueryTimeout")).on(config))
                    .method(named("setFetchSize").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setFetchSize", int.class)).on(config).withAllArguments())
                    .method(named("getFetchSize").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getFetchSize")).on(config))
                    .method(named("setFetchDirection").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setFetchDirection", int.class)).on(config).withAllArguments())
                    .method(named("getFetchDirection").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getFetchDirection")).on(config))
                    .method(named("getResultSetType").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getResultSetType")).on(config))
                    .method(named("getResultSetConcurrency").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getResultSetConcurrency")).on(config))
                    .method(named("getResultSetHoldability").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getResultSetHoldability")).on(config))
                    .method(named("executeQuery").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeQuery", String.class)).on(query).withAllArguments())
                    .method(named("execute").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("execute", String.class)).on(query).withAllArguments())
                    .method(named("execute").and(takesArguments(String.class, int.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("execute", String.class, int.class)).on(query).withAllArguments())
                    .method(named("execute").and(takesArguments(String.class, int[].class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("execute", String.class, int[].class)).on(query).withAllArguments())
                    .method(named("execute").and(takesArguments(String.class, String[].class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("execute", String.class, String[].class)).on(query).withAllArguments())
                    .method(named("executeUpdate").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeUpdate", String.class)).on(query).withAllArguments())
                    .method(named("executeUpdate").and(takesArguments(String.class, int.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeUpdate", String.class, int.class)).on(query).withAllArguments())
                    .method(named("executeUpdate").and(takesArguments(String.class, int[].class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeUpdate", String.class, int[].class)).on(query).withAllArguments())
                    .method(named("executeUpdate").and(takesArguments(String.class, String[].class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeUpdate", String.class, String[].class)).on(query).withAllArguments())
                    .method(named("executeLargeUpdate").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeLargeUpdate", String.class)).on(query).withAllArguments())
                    .method(named("executeLargeUpdate").and(takesArguments(String.class, int.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeLargeUpdate", String.class, int.class)).on(query).withAllArguments())
                    .method(named("executeLargeUpdate").and(takesArguments(String.class, int[].class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeLargeUpdate", String.class, int[].class)).on(query).withAllArguments())
                    .method(named("executeLargeUpdate").and(takesArguments(String.class, String[].class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeLargeUpdate", String.class, String[].class)).on(query).withAllArguments())
                    .method(named("addBatch").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("addBatch", String.class)).on(query).withAllArguments())
                    .method(named("clearBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("clearBatch")).on(query))
                    .method(named("executeBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeBatch")).on(query))
                    .method(named("executeLargeBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeLargeBatch")).on(query))
                    .method(named("getResultSet").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("getResultSet")).on(query))
                    .method(named("getUpdateCount").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("getUpdateCount")).on(query))
                    .method(named("getLargeUpdateCount").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("getLargeUpdateCount")).on(query))
                    .method(named("getGeneratedKeys").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("getGeneratedKeys")).on(query))
                    .method(named("getMoreResults").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("getMoreResults")).on(query))
                    .method(named("getMoreResults").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("getMoreResults", int.class)).on(query).withAllArguments())
                    .method(named("closeOnCompletion").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("closeOnCompletion")).on(query))
                    .method(named("isCloseOnCompletion").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("isCloseOnCompletion")).on(query))
                    .make()) {
                return unloaded.load(StatementFactory.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                        .getLoaded()
                        .getDeclaredConstructor()
                        .newInstance();
            }
        } catch (Exception e) {
            throw new SQLException("Failed to create mock Statement", e);
        }
    }

    private PreparedStatement buildPreparedStatement(String sql, boolean returnGeneratedKeys) throws SQLException {
        try {
            var lifecycle = new StatementLifecycleHandler();
            var warnings = new StatementWarningsHandler();
            var config = new StatementConfigHandler();
            var executionState = new StatementExecutionStateHandler();
            var generatedKeys = new GeneratedKeysHandler();
            var misc = new StatementMiscHandler(mockConfig, lifecycle);
            var prepared = new PreparedStatementQueryHandler(mockConfig, lifecycle, executionState, generatedKeys, returnGeneratedKeys, sql);

            var typeName = StatementFactory.class.getPackageName() + ".MockPreparedStatement$" + PREPARED_STATEMENT_SEQUENCE.incrementAndGet();

            try (var unloaded = new ByteBuddy()
                    .subclass(PreparedStatement.class)
                    .name(typeName)
                    .method(named("close").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("close")).on(lifecycle))
                    .method(named("isClosed").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("isClosed")).on(lifecycle))
                    .method(named("setPoolable").and(takesArguments(boolean.class)))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("setPoolable", boolean.class)).on(misc).withAllArguments())
                    .method(named("isPoolable").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("isPoolable")).on(misc))
                    .method(named("setEscapeProcessing").and(takesArguments(boolean.class)))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("setEscapeProcessing", boolean.class)).on(misc).withAllArguments())
                    .method(named("setCursorName").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("setCursorName", String.class)).on(misc).withAllArguments())
                    .method(named("cancel").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("cancel")).on(misc))
                    .method(named("getConnection").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("getConnection")).on(misc))
                    .method(named("getWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("getWarnings")).on(warnings))
                    .method(named("clearWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("clearWarnings")).on(warnings))
                    .method(named("setMaxRows").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setMaxRows", int.class)).on(config).withAllArguments())
                    .method(named("getMaxRows").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getMaxRows")).on(config))
                    .method(named("setLargeMaxRows").and(takesArguments(long.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setLargeMaxRows", long.class)).on(config).withAllArguments())
                    .method(named("getLargeMaxRows").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getLargeMaxRows")).on(config))
                    .method(named("setQueryTimeout").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setQueryTimeout", int.class)).on(config).withAllArguments())
                    .method(named("getQueryTimeout").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getQueryTimeout")).on(config))
                    .method(named("setFetchSize").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setFetchSize", int.class)).on(config).withAllArguments())
                    .method(named("getFetchSize").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getFetchSize")).on(config))
                    .method(named("setFetchDirection").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setFetchDirection", int.class)).on(config).withAllArguments())
                    .method(named("getFetchDirection").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getFetchDirection")).on(config))
                    .method(named("getResultSetType").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getResultSetType")).on(config))
                    .method(named("getResultSetConcurrency").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getResultSetConcurrency")).on(config))
                    .method(named("getResultSetHoldability").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getResultSetHoldability")).on(config))
                    .method(named("setString").and(takesArguments(int.class, String.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setString", int.class, String.class)).on(prepared).withAllArguments())
                    .method(named("setInt").and(takesArguments(int.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setInt", int.class, int.class)).on(prepared).withAllArguments())
                    .method(named("setLong").and(takesArguments(int.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setLong", int.class, long.class)).on(prepared).withAllArguments())
                    .method(named("setBoolean").and(takesArguments(int.class, boolean.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBoolean", int.class, boolean.class)).on(prepared).withAllArguments())
                    .method(named("setDouble").and(takesArguments(int.class, double.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setDouble", int.class, double.class)).on(prepared).withAllArguments())
                    .method(named("setFloat").and(takesArguments(int.class, float.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setFloat", int.class, float.class)).on(prepared).withAllArguments())
                    .method(named("setShort").and(takesArguments(int.class, short.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setShort", int.class, short.class)).on(prepared).withAllArguments())
                    .method(named("setByte").and(takesArguments(int.class, byte.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setByte", int.class, byte.class)).on(prepared).withAllArguments())
                    .method(named("setBytes").and(takesArguments(int.class, byte[].class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBytes", int.class, byte[].class)).on(prepared).withAllArguments())
                    .method(named("setBigDecimal").and(takesArguments(int.class, java.math.BigDecimal.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBigDecimal", int.class, java.math.BigDecimal.class)).on(prepared).withAllArguments())
                    .method(named("setDate").and(takesArguments(int.class, java.sql.Date.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setDate", int.class, java.sql.Date.class)).on(prepared).withAllArguments())
                    .method(named("setTime").and(takesArguments(int.class, java.sql.Time.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setTime", int.class, java.sql.Time.class)).on(prepared).withAllArguments())
                    .method(named("setTimestamp").and(takesArguments(int.class, java.sql.Timestamp.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setTimestamp", int.class, java.sql.Timestamp.class)).on(prepared).withAllArguments())
                    .method(named("setObject").and(takesArguments(int.class, Object.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setObject", int.class, Object.class)).on(prepared).withAllArguments())
                    .method(named("setObject").and(takesArguments(int.class, Object.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setObject", int.class, Object.class, int.class)).on(prepared).withAllArguments())
                    .method(named("setObject").and(takesArguments(int.class, Object.class, int.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setObject", int.class, Object.class, int.class, int.class)).on(prepared).withAllArguments())
                    .method(named("setNull").and(takesArguments(int.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNull", int.class, int.class)).on(prepared).withAllArguments())
                    .method(named("setNull").and(takesArguments(int.class, int.class, String.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNull", int.class, int.class, String.class)).on(prepared).withAllArguments())
                    .method(named("setDate").and(takesArguments(int.class, java.sql.Date.class, Calendar.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setDate", int.class, java.sql.Date.class, Calendar.class)).on(prepared).withAllArguments())
                    .method(named("setTime").and(takesArguments(int.class, java.sql.Time.class, Calendar.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setTime", int.class, java.sql.Time.class, Calendar.class)).on(prepared).withAllArguments())
                    .method(named("setTimestamp").and(takesArguments(int.class, java.sql.Timestamp.class, Calendar.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setTimestamp", int.class, java.sql.Timestamp.class, Calendar.class)).on(prepared).withAllArguments())
                    .method(named("getParameterMetaData").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getParameterMetaData")).on(prepared))
                    .method(named("getMetaData").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getMetaData")).on(prepared))
                    .method(named("setURL").and(takesArguments(int.class, java.net.URL.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setURL", int.class, java.net.URL.class)).on(prepared).withAllArguments())
                    .method(named("setRowId").and(takesArguments(int.class, java.sql.RowId.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setRowId", int.class, java.sql.RowId.class)).on(prepared).withAllArguments())
                    .method(named("setSQLXML").and(takesArguments(int.class, java.sql.SQLXML.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setSQLXML", int.class, java.sql.SQLXML.class)).on(prepared).withAllArguments())
                    .method(named("setNString").and(takesArguments(int.class, String.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNString", int.class, String.class)).on(prepared).withAllArguments())
                    .method(named("setBlob").and(takesArguments(int.class, java.sql.Blob.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBlob", int.class, java.sql.Blob.class)).on(prepared).withAllArguments())
                    .method(named("setBlob").and(takesArguments(int.class, java.io.InputStream.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBlob", int.class, java.io.InputStream.class)).on(prepared).withAllArguments())
                    .method(named("setBlob").and(takesArguments(int.class, java.io.InputStream.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBlob", int.class, java.io.InputStream.class, long.class)).on(prepared).withAllArguments())
                    .method(named("setClob").and(takesArguments(int.class, java.sql.Clob.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setClob", int.class, java.sql.Clob.class)).on(prepared).withAllArguments())
                    .method(named("setClob").and(takesArguments(int.class, java.io.Reader.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setClob", int.class, java.io.Reader.class)).on(prepared).withAllArguments())
                    .method(named("setClob").and(takesArguments(int.class, java.io.Reader.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setClob", int.class, java.io.Reader.class, long.class)).on(prepared).withAllArguments())
                    .method(named("setNClob").and(takesArguments(int.class, java.sql.NClob.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNClob", int.class, java.sql.NClob.class)).on(prepared).withAllArguments())
                    .method(named("setNClob").and(takesArguments(int.class, java.io.Reader.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNClob", int.class, java.io.Reader.class)).on(prepared).withAllArguments())
                    .method(named("setNClob").and(takesArguments(int.class, java.io.Reader.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNClob", int.class, java.io.Reader.class, long.class)).on(prepared).withAllArguments())
                    .method(named("setArray").and(takesArguments(int.class, java.sql.Array.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setArray", int.class, java.sql.Array.class)).on(prepared).withAllArguments())
                    .method(named("setRef").and(takesArguments(int.class, java.sql.Ref.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setRef", int.class, java.sql.Ref.class)).on(prepared).withAllArguments())
                    .method(named("setBinaryStream").and(takesArguments(int.class, java.io.InputStream.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBinaryStream", int.class, java.io.InputStream.class)).on(prepared).withAllArguments())
                    .method(named("setBinaryStream").and(takesArguments(int.class, java.io.InputStream.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBinaryStream", int.class, java.io.InputStream.class, int.class)).on(prepared).withAllArguments())
                    .method(named("setBinaryStream").and(takesArguments(int.class, java.io.InputStream.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBinaryStream", int.class, java.io.InputStream.class, long.class)).on(prepared).withAllArguments())
                    .method(named("setCharacterStream").and(takesArguments(int.class, java.io.Reader.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setCharacterStream", int.class, java.io.Reader.class)).on(prepared).withAllArguments())
                    .method(named("setCharacterStream").and(takesArguments(int.class, java.io.Reader.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setCharacterStream", int.class, java.io.Reader.class, int.class)).on(prepared).withAllArguments())
                    .method(named("setCharacterStream").and(takesArguments(int.class, java.io.Reader.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setCharacterStream", int.class, java.io.Reader.class, long.class)).on(prepared).withAllArguments())
                    .method(named("setNCharacterStream").and(takesArguments(int.class, java.io.Reader.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNCharacterStream", int.class, java.io.Reader.class)).on(prepared).withAllArguments())
                    .method(named("setNCharacterStream").and(takesArguments(int.class, java.io.Reader.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNCharacterStream", int.class, java.io.Reader.class, long.class)).on(prepared).withAllArguments())
                    .method(named("setAsciiStream").and(takesArguments(int.class, java.io.InputStream.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setAsciiStream", int.class, java.io.InputStream.class)).on(prepared).withAllArguments())
                    .method(named("setAsciiStream").and(takesArguments(int.class, java.io.InputStream.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setAsciiStream", int.class, java.io.InputStream.class, int.class)).on(prepared).withAllArguments())
                    .method(named("setAsciiStream").and(takesArguments(int.class, java.io.InputStream.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setAsciiStream", int.class, java.io.InputStream.class, long.class)).on(prepared).withAllArguments())
                    .method(named("setUnicodeStream").and(takesArguments(int.class, java.io.InputStream.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setUnicodeStream", int.class, java.io.InputStream.class, int.class)).on(prepared).withAllArguments())
                    .method(named("addBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("addBatch")).on(prepared))
                    .method(named("clearBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("clearBatch")).on(prepared))
                    .method(named("executeBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeBatch")).on(prepared))
                    .method(named("executeLargeBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeLargeBatch")).on(prepared))
                    .method(named("clearParameters").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("clearParameters")).on(prepared))
                    .method(named("executeQuery").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeQuery")).on(prepared))
                    .method(named("execute").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("execute")).on(prepared))
                    .method(named("executeUpdate").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeUpdate")).on(prepared))
                    .method(named("executeLargeUpdate").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeLargeUpdate")).on(prepared))
                    .method(named("getResultSet").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getResultSet")).on(prepared))
                    .method(named("getUpdateCount").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getUpdateCount")).on(prepared))
                    .method(named("getLargeUpdateCount").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getLargeUpdateCount")).on(prepared))
                    .method(named("getGeneratedKeys").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getGeneratedKeys")).on(prepared))
                    .method(named("getMoreResults").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getMoreResults")).on(prepared))
                    .method(named("getMoreResults").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getMoreResults", int.class)).on(prepared).withAllArguments())
                    .method(named("closeOnCompletion").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("closeOnCompletion")).on(prepared))
                    .method(named("isCloseOnCompletion").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("isCloseOnCompletion")).on(prepared))
                    .make()) {
                return unloaded.load(StatementFactory.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                        .getLoaded()
                        .getDeclaredConstructor()
                        .newInstance();
            }
        } catch (Exception e) {
            throw new SQLException("Failed to create mock PreparedStatement", e);
        }
    }

    private CallableStatement buildCallableStatement(String sql) throws SQLException {
        try {
            var lifecycle = new StatementLifecycleHandler();
            var warnings = new StatementWarningsHandler();
            var config = new StatementConfigHandler();
            var executionState = new StatementExecutionStateHandler();
            var generatedKeys = new GeneratedKeysHandler();
            var misc = new StatementMiscHandler(mockConfig, lifecycle);
            var callable = new PreparedStatementQueryHandler(mockConfig, lifecycle, executionState, generatedKeys, false, sql);
            var outParams = new CallableStatementOutParamHandler(lifecycle);

            var typeName = StatementFactory.class.getPackageName() + ".MockCallableStatement$" + CALLABLE_STATEMENT_SEQUENCE.incrementAndGet();

            try (var unloaded = new ByteBuddy()
                    .subclass(CallableStatement.class)
                    .name(typeName)
                    .method(named("close").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("close")).on(lifecycle))
                    .method(named("isClosed").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("isClosed")).on(lifecycle))
                    .method(named("setPoolable").and(takesArguments(boolean.class)))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("setPoolable", boolean.class)).on(misc).withAllArguments())
                    .method(named("isPoolable").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("isPoolable")).on(misc))
                    .method(named("setEscapeProcessing").and(takesArguments(boolean.class)))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("setEscapeProcessing", boolean.class)).on(misc).withAllArguments())
                    .method(named("setCursorName").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("setCursorName", String.class)).on(misc).withAllArguments())
                    .method(named("cancel").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("cancel")).on(misc))
                    .method(named("getConnection").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementMiscHandler.class.getMethod("getConnection")).on(misc))
                    .method(named("getWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("getWarnings")).on(warnings))
                    .method(named("clearWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("clearWarnings")).on(warnings))
                    .method(named("setMaxRows").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setMaxRows", int.class)).on(config).withAllArguments())
                    .method(named("getMaxRows").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getMaxRows")).on(config))
                    .method(named("setLargeMaxRows").and(takesArguments(long.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setLargeMaxRows", long.class)).on(config).withAllArguments())
                    .method(named("getLargeMaxRows").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getLargeMaxRows")).on(config))
                    .method(named("setQueryTimeout").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setQueryTimeout", int.class)).on(config).withAllArguments())
                    .method(named("getQueryTimeout").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getQueryTimeout")).on(config))
                    .method(named("setFetchSize").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setFetchSize", int.class)).on(config).withAllArguments())
                    .method(named("getFetchSize").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getFetchSize")).on(config))
                    .method(named("setFetchDirection").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("setFetchDirection", int.class)).on(config).withAllArguments())
                    .method(named("getFetchDirection").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getFetchDirection")).on(config))
                    .method(named("getResultSetType").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getResultSetType")).on(config))
                    .method(named("getResultSetConcurrency").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getResultSetConcurrency")).on(config))
                    .method(named("getResultSetHoldability").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementConfigHandler.class.getMethod("getResultSetHoldability")).on(config))
                    .method(named("setString").and(takesArguments(int.class, String.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setString", int.class, String.class)).on(callable).withAllArguments())
                    .method(named("setInt").and(takesArguments(int.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setInt", int.class, int.class)).on(callable).withAllArguments())
                    .method(named("setLong").and(takesArguments(int.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setLong", int.class, long.class)).on(callable).withAllArguments())
                    .method(named("setBoolean").and(takesArguments(int.class, boolean.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBoolean", int.class, boolean.class)).on(callable).withAllArguments())
                    .method(named("setDouble").and(takesArguments(int.class, double.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setDouble", int.class, double.class)).on(callable).withAllArguments())
                    .method(named("setFloat").and(takesArguments(int.class, float.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setFloat", int.class, float.class)).on(callable).withAllArguments())
                    .method(named("setShort").and(takesArguments(int.class, short.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setShort", int.class, short.class)).on(callable).withAllArguments())
                    .method(named("setByte").and(takesArguments(int.class, byte.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setByte", int.class, byte.class)).on(callable).withAllArguments())
                    .method(named("setBytes").and(takesArguments(int.class, byte[].class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBytes", int.class, byte[].class)).on(callable).withAllArguments())
                    .method(named("setBigDecimal").and(takesArguments(int.class, java.math.BigDecimal.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBigDecimal", int.class, java.math.BigDecimal.class)).on(callable).withAllArguments())
                    .method(named("setDate").and(takesArguments(int.class, java.sql.Date.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setDate", int.class, java.sql.Date.class)).on(callable).withAllArguments())
                    .method(named("setTime").and(takesArguments(int.class, java.sql.Time.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setTime", int.class, java.sql.Time.class)).on(callable).withAllArguments())
                    .method(named("setTimestamp").and(takesArguments(int.class, java.sql.Timestamp.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setTimestamp", int.class, java.sql.Timestamp.class)).on(callable).withAllArguments())
                    .method(named("setObject").and(takesArguments(int.class, Object.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setObject", int.class, Object.class)).on(callable).withAllArguments())
                    .method(named("setObject").and(takesArguments(int.class, Object.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setObject", int.class, Object.class, int.class)).on(callable).withAllArguments())
                    .method(named("setObject").and(takesArguments(int.class, Object.class, int.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setObject", int.class, Object.class, int.class, int.class)).on(callable).withAllArguments())
                    .method(named("setNull").and(takesArguments(int.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNull", int.class, int.class)).on(callable).withAllArguments())
                    .method(named("setNull").and(takesArguments(int.class, int.class, String.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNull", int.class, int.class, String.class)).on(callable).withAllArguments())
                    .method(named("setDate").and(takesArguments(int.class, java.sql.Date.class, Calendar.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setDate", int.class, java.sql.Date.class, Calendar.class)).on(callable).withAllArguments())
                    .method(named("setTime").and(takesArguments(int.class, java.sql.Time.class, Calendar.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setTime", int.class, java.sql.Time.class, Calendar.class)).on(callable).withAllArguments())
                    .method(named("setTimestamp").and(takesArguments(int.class, java.sql.Timestamp.class, Calendar.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setTimestamp", int.class, java.sql.Timestamp.class, Calendar.class)).on(callable).withAllArguments())
                    .method(named("getParameterMetaData").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getParameterMetaData")).on(callable))
                    .method(named("getMetaData").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getMetaData")).on(callable))
                    .method(named("setURL").and(takesArguments(int.class, java.net.URL.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setURL", int.class, java.net.URL.class)).on(callable).withAllArguments())
                    .method(named("setRowId").and(takesArguments(int.class, java.sql.RowId.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setRowId", int.class, java.sql.RowId.class)).on(callable).withAllArguments())
                    .method(named("setSQLXML").and(takesArguments(int.class, java.sql.SQLXML.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setSQLXML", int.class, java.sql.SQLXML.class)).on(callable).withAllArguments())
                    .method(named("setNString").and(takesArguments(int.class, String.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNString", int.class, String.class)).on(callable).withAllArguments())
                    .method(named("setBlob").and(takesArguments(int.class, java.sql.Blob.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBlob", int.class, java.sql.Blob.class)).on(callable).withAllArguments())
                    .method(named("setBlob").and(takesArguments(int.class, java.io.InputStream.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBlob", int.class, java.io.InputStream.class)).on(callable).withAllArguments())
                    .method(named("setBlob").and(takesArguments(int.class, java.io.InputStream.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBlob", int.class, java.io.InputStream.class, long.class)).on(callable).withAllArguments())
                    .method(named("setClob").and(takesArguments(int.class, java.sql.Clob.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setClob", int.class, java.sql.Clob.class)).on(callable).withAllArguments())
                    .method(named("setClob").and(takesArguments(int.class, java.io.Reader.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setClob", int.class, java.io.Reader.class)).on(callable).withAllArguments())
                    .method(named("setClob").and(takesArguments(int.class, java.io.Reader.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setClob", int.class, java.io.Reader.class, long.class)).on(callable).withAllArguments())
                    .method(named("setNClob").and(takesArguments(int.class, java.sql.NClob.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNClob", int.class, java.sql.NClob.class)).on(callable).withAllArguments())
                    .method(named("setNClob").and(takesArguments(int.class, java.io.Reader.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNClob", int.class, java.io.Reader.class)).on(callable).withAllArguments())
                    .method(named("setNClob").and(takesArguments(int.class, java.io.Reader.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNClob", int.class, java.io.Reader.class, long.class)).on(callable).withAllArguments())
                    .method(named("setArray").and(takesArguments(int.class, java.sql.Array.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setArray", int.class, java.sql.Array.class)).on(callable).withAllArguments())
                    .method(named("setRef").and(takesArguments(int.class, java.sql.Ref.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setRef", int.class, java.sql.Ref.class)).on(callable).withAllArguments())
                    .method(named("setBinaryStream").and(takesArguments(int.class, java.io.InputStream.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBinaryStream", int.class, java.io.InputStream.class)).on(callable).withAllArguments())
                    .method(named("setBinaryStream").and(takesArguments(int.class, java.io.InputStream.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBinaryStream", int.class, java.io.InputStream.class, int.class)).on(callable).withAllArguments())
                    .method(named("setBinaryStream").and(takesArguments(int.class, java.io.InputStream.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBinaryStream", int.class, java.io.InputStream.class, long.class)).on(callable).withAllArguments())
                    .method(named("setCharacterStream").and(takesArguments(int.class, java.io.Reader.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setCharacterStream", int.class, java.io.Reader.class)).on(callable).withAllArguments())
                    .method(named("setCharacterStream").and(takesArguments(int.class, java.io.Reader.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setCharacterStream", int.class, java.io.Reader.class, int.class)).on(callable).withAllArguments())
                    .method(named("setCharacterStream").and(takesArguments(int.class, java.io.Reader.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setCharacterStream", int.class, java.io.Reader.class, long.class)).on(callable).withAllArguments())
                    .method(named("setNCharacterStream").and(takesArguments(int.class, java.io.Reader.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNCharacterStream", int.class, java.io.Reader.class)).on(callable).withAllArguments())
                    .method(named("setNCharacterStream").and(takesArguments(int.class, java.io.Reader.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNCharacterStream", int.class, java.io.Reader.class, long.class)).on(callable).withAllArguments())
                    .method(named("setAsciiStream").and(takesArguments(int.class, java.io.InputStream.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setAsciiStream", int.class, java.io.InputStream.class)).on(callable).withAllArguments())
                    .method(named("setAsciiStream").and(takesArguments(int.class, java.io.InputStream.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setAsciiStream", int.class, java.io.InputStream.class, int.class)).on(callable).withAllArguments())
                    .method(named("setAsciiStream").and(takesArguments(int.class, java.io.InputStream.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setAsciiStream", int.class, java.io.InputStream.class, long.class)).on(callable).withAllArguments())
                    .method(named("setUnicodeStream").and(takesArguments(int.class, java.io.InputStream.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setUnicodeStream", int.class, java.io.InputStream.class, int.class)).on(callable).withAllArguments())
                    .method(named("addBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("addBatch")).on(callable))
                    .method(named("clearBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("clearBatch")).on(callable))
                    .method(named("executeBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeBatch")).on(callable))
                    .method(named("executeLargeBatch").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeLargeBatch")).on(callable))
                    .method(named("clearParameters").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("clearParameters")).on(callable))
                    .method(named("executeQuery").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeQuery")).on(callable))
                    .method(named("execute").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("execute")).on(callable))
                    .method(named("executeUpdate").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeUpdate")).on(callable))
                    .method(named("executeLargeUpdate").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeLargeUpdate")).on(callable))
                    .method(named("getResultSet").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getResultSet")).on(callable))
                    .method(named("getUpdateCount").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getUpdateCount")).on(callable))
                    .method(named("getLargeUpdateCount").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getLargeUpdateCount")).on(callable))
                    .method(named("getGeneratedKeys").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getGeneratedKeys")).on(callable))
                    .method(named("getMoreResults").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getMoreResults")).on(callable))
                    .method(named("getMoreResults").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getMoreResults", int.class)).on(callable).withAllArguments())
                    .method(named("closeOnCompletion").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("closeOnCompletion")).on(callable))
                    .method(named("isCloseOnCompletion").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("isCloseOnCompletion")).on(callable))
                    // OUT params
                    .method(named("registerOutParameter").and(takesArguments(int.class, int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("registerOutParameter", int.class, int.class)).on(outParams).withAllArguments())
                    .method(named("registerOutParameter").and(takesArguments(int.class, int.class, int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("registerOutParameter", int.class, int.class, int.class)).on(outParams).withAllArguments())
                    .method(named("registerOutParameter").and(takesArguments(int.class, int.class, String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("registerOutParameter", int.class, int.class, String.class)).on(outParams).withAllArguments())
                    .method(named("registerOutParameter").and(takesArguments(String.class, int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("registerOutParameter", String.class, int.class)).on(outParams).withAllArguments())
                    .method(named("registerOutParameter").and(takesArguments(String.class, int.class, int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("registerOutParameter", String.class, int.class, int.class)).on(outParams).withAllArguments())
                    .method(named("registerOutParameter").and(takesArguments(String.class, int.class, String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("registerOutParameter", String.class, int.class, String.class)).on(outParams).withAllArguments())
                    .method(named("wasNull").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("wasNull")).on(outParams))
                    // getters by index
                    .method(named("getString").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getString", int.class)).on(outParams).withAllArguments())
                    .method(named("getBoolean").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getBoolean", int.class)).on(outParams).withAllArguments())
                    .method(named("getByte").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getByte", int.class)).on(outParams).withAllArguments())
                    .method(named("getShort").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getShort", int.class)).on(outParams).withAllArguments())
                    .method(named("getInt").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getInt", int.class)).on(outParams).withAllArguments())
                    .method(named("getLong").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getLong", int.class)).on(outParams).withAllArguments())
                    .method(named("getFloat").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getFloat", int.class)).on(outParams).withAllArguments())
                    .method(named("getDouble").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getDouble", int.class)).on(outParams).withAllArguments())
                    .method(named("getBytes").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getBytes", int.class)).on(outParams).withAllArguments())
                    .method(named("getBigDecimal").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getBigDecimal", int.class)).on(outParams).withAllArguments())
                    .method(named("getObject").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getObject", int.class)).on(outParams).withAllArguments())
                    .method(named("getDate").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getDate", int.class)).on(outParams).withAllArguments())
                    .method(named("getDate").and(takesArguments(int.class, Calendar.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getDate", int.class, Calendar.class)).on(outParams).withAllArguments())
                    .method(named("getTime").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getTime", int.class)).on(outParams).withAllArguments())
                    .method(named("getTime").and(takesArguments(int.class, Calendar.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getTime", int.class, Calendar.class)).on(outParams).withAllArguments())
                    .method(named("getTimestamp").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getTimestamp", int.class)).on(outParams).withAllArguments())
                    .method(named("getTimestamp").and(takesArguments(int.class, Calendar.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getTimestamp", int.class, Calendar.class)).on(outParams).withAllArguments())
                    .method(named("getObject").and(takesArguments(int.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getObject", int.class)).on(outParams).withAllArguments())
                    .method(named("getObject").and(takesArguments(int.class, Class.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getObject", int.class, Class.class)).on(outParams).withAllArguments())
                    // getters by name
                    .method(named("getString").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getString", String.class)).on(outParams).withAllArguments())
                    .method(named("getBoolean").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getBoolean", String.class)).on(outParams).withAllArguments())
                    .method(named("getByte").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getByte", String.class)).on(outParams).withAllArguments())
                    .method(named("getShort").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getShort", String.class)).on(outParams).withAllArguments())
                    .method(named("getInt").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getInt", String.class)).on(outParams).withAllArguments())
                    .method(named("getLong").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getLong", String.class)).on(outParams).withAllArguments())
                    .method(named("getFloat").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getFloat", String.class)).on(outParams).withAllArguments())
                    .method(named("getDouble").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getDouble", String.class)).on(outParams).withAllArguments())
                    .method(named("getBytes").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getBytes", String.class)).on(outParams).withAllArguments())
                    .method(named("getBigDecimal").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getBigDecimal", String.class)).on(outParams).withAllArguments())
                    .method(named("getObject").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getObject", String.class)).on(outParams).withAllArguments())
                    .method(named("getDate").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getDate", String.class)).on(outParams).withAllArguments())
                    .method(named("getDate").and(takesArguments(String.class, Calendar.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getDate", String.class, Calendar.class)).on(outParams).withAllArguments())
                    .method(named("getTime").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getTime", String.class)).on(outParams).withAllArguments())
                    .method(named("getTime").and(takesArguments(String.class, Calendar.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getTime", String.class, Calendar.class)).on(outParams).withAllArguments())
                    .method(named("getTimestamp").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getTimestamp", String.class)).on(outParams).withAllArguments())
                    .method(named("getTimestamp").and(takesArguments(String.class, Calendar.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getTimestamp", String.class, Calendar.class)).on(outParams).withAllArguments())
                    .method(named("getObject").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getObject", String.class)).on(outParams).withAllArguments())
                    .method(named("getObject").and(takesArguments(String.class, Class.class)))
                    .intercept(MethodCall.invoke(CallableStatementOutParamHandler.class.getMethod("getObject", String.class, Class.class)).on(outParams).withAllArguments())
                    .make()) {
                return unloaded.load(StatementFactory.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                        .getLoaded()
                        .getDeclaredConstructor()
                        .newInstance();
            }
        } catch (Exception e) {
            throw new SQLException("Failed to create mock CallableStatement", e);
        }
    }
}
