package io.github.rroyoo.mockjdbc.mock.statement;

import io.github.rroyoo.mockjdbc.mock.driver.MockConfig;
import net.bytebuddy.ByteBuddy;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.implementation.MethodCall;

import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicLong;

import static net.bytebuddy.matcher.ElementMatchers.named;
import static net.bytebuddy.matcher.ElementMatchers.takesArguments;
import static net.bytebuddy.matcher.ElementMatchers.takesNoArguments;

public final class StatementFactory {

    private static final AtomicLong STATEMENT_SEQUENCE = new AtomicLong(0L);
    private static final AtomicLong PREPARED_STATEMENT_SEQUENCE = new AtomicLong(0L);
    private static final AtomicLong CALLABLE_STATEMENT_SEQUENCE = new AtomicLong(0L);

    private final MockConfig mockConfig;

    public StatementFactory(MockConfig mockConfig) {
        if (mockConfig == null) {
            throw new IllegalArgumentException("MockConfig cannot be null");
        }
        this.mockConfig = mockConfig;
    }

    public Statement createStatement() throws SQLException {
        return buildStatement();
    }

    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return buildStatement();
    }

    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return buildStatement();
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return buildPreparedStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return buildPreparedStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return buildPreparedStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return buildPreparedStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return buildPreparedStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return buildPreparedStatement(sql);
    }

    public CallableStatement prepareCall(String sql) throws SQLException {
        return buildCallableStatement(sql);
    }

    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return buildCallableStatement(sql);
    }

    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return buildCallableStatement(sql);
    }

    private Statement buildStatement() throws SQLException {
        try {
            var lifecycle = new StatementLifecycleHandler();
            var warnings = new StatementWarningsHandler();
            var executionState = new StatementExecutionStateHandler();
            var query = new StatementQueryHandler(mockConfig, lifecycle, executionState);

            var typeName = StatementFactory.class.getPackageName() + ".MockStatement$" + STATEMENT_SEQUENCE.incrementAndGet();

            try (var unloaded = new ByteBuddy()
                    .subclass(Statement.class)
                    .name(typeName)
                    .method(named("close").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("close")).on(lifecycle))
                    .method(named("isClosed").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("isClosed")).on(lifecycle))
                    .method(named("getWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("getWarnings")).on(warnings))
                    .method(named("clearWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("clearWarnings")).on(warnings))
                    .method(named("executeQuery").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("executeQuery", String.class)).on(query).withAllArguments())
                    .method(named("execute").and(takesArguments(String.class)))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("execute", String.class)).on(query).withAllArguments())
                    .method(named("getResultSet").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("getResultSet")).on(query))
                    .method(named("getUpdateCount").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("getUpdateCount")).on(query))
                    .method(named("getMoreResults").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementQueryHandler.class.getMethod("getMoreResults")).on(query))
                    .make()) {
                return unloaded.load(StatementFactory.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                        .getLoaded()
                        .getDeclaredConstructor()
                        .newInstance();
            }
        } catch (Exception e) {
            throw new SQLException("Failed to create mock Statement", e);
        }
    }

    private PreparedStatement buildPreparedStatement(String sql) throws SQLException {
        try {
            var lifecycle = new StatementLifecycleHandler();
            var warnings = new StatementWarningsHandler();
            var executionState = new StatementExecutionStateHandler();
            var prepared = new PreparedStatementQueryHandler(mockConfig, lifecycle, executionState, sql);

            var typeName = StatementFactory.class.getPackageName() + ".MockPreparedStatement$" + PREPARED_STATEMENT_SEQUENCE.incrementAndGet();

            try (var unloaded = new ByteBuddy()
                    .subclass(PreparedStatement.class)
                    .name(typeName)
                    .method(named("close").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("close")).on(lifecycle))
                    .method(named("isClosed").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("isClosed")).on(lifecycle))
                    .method(named("getWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("getWarnings")).on(warnings))
                    .method(named("clearWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("clearWarnings")).on(warnings))
                    .method(named("setString").and(takesArguments(int.class, String.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setString", int.class, String.class)).on(prepared).withAllArguments())
                    .method(named("setInt").and(takesArguments(int.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setInt", int.class, int.class)).on(prepared).withAllArguments())
                    .method(named("setLong").and(takesArguments(int.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setLong", int.class, long.class)).on(prepared).withAllArguments())
                    .method(named("setBoolean").and(takesArguments(int.class, boolean.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBoolean", int.class, boolean.class)).on(prepared).withAllArguments())
                    .method(named("setObject").and(takesArguments(int.class, Object.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setObject", int.class, Object.class)).on(prepared).withAllArguments())
                    .method(named("setNull").and(takesArguments(int.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNull", int.class, int.class)).on(prepared).withAllArguments())
                    .method(named("clearParameters").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("clearParameters")).on(prepared))
                    .method(named("executeQuery").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeQuery")).on(prepared))
                    .method(named("execute").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("execute")).on(prepared))
                    .method(named("getResultSet").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getResultSet")).on(prepared))
                    .method(named("getUpdateCount").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getUpdateCount")).on(prepared))
                    .method(named("getMoreResults").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getMoreResults")).on(prepared))
                    .make()) {
                return unloaded.load(StatementFactory.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                        .getLoaded()
                        .getDeclaredConstructor()
                        .newInstance();
            }
        } catch (Exception e) {
            throw new SQLException("Failed to create mock PreparedStatement", e);
        }
    }

    private CallableStatement buildCallableStatement(String sql) throws SQLException {
        try {
            var lifecycle = new StatementLifecycleHandler();
            var warnings = new StatementWarningsHandler();
            var executionState = new StatementExecutionStateHandler();
            var callable = new PreparedStatementQueryHandler(mockConfig, lifecycle, executionState, sql);

            var typeName = StatementFactory.class.getPackageName() + ".MockCallableStatement$" + CALLABLE_STATEMENT_SEQUENCE.incrementAndGet();

            try (var unloaded = new ByteBuddy()
                    .subclass(CallableStatement.class)
                    .name(typeName)
                    .method(named("close").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("close")).on(lifecycle))
                    .method(named("isClosed").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementLifecycleHandler.class.getMethod("isClosed")).on(lifecycle))
                    .method(named("getWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("getWarnings")).on(warnings))
                    .method(named("clearWarnings").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(StatementWarningsHandler.class.getMethod("clearWarnings")).on(warnings))
                    .method(named("setString").and(takesArguments(int.class, String.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setString", int.class, String.class)).on(callable).withAllArguments())
                    .method(named("setInt").and(takesArguments(int.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setInt", int.class, int.class)).on(callable).withAllArguments())
                    .method(named("setLong").and(takesArguments(int.class, long.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setLong", int.class, long.class)).on(callable).withAllArguments())
                    .method(named("setBoolean").and(takesArguments(int.class, boolean.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setBoolean", int.class, boolean.class)).on(callable).withAllArguments())
                    .method(named("setObject").and(takesArguments(int.class, Object.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setObject", int.class, Object.class)).on(callable).withAllArguments())
                    .method(named("setNull").and(takesArguments(int.class, int.class)))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("setNull", int.class, int.class)).on(callable).withAllArguments())
                    .method(named("clearParameters").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("clearParameters")).on(callable))
                    .method(named("executeQuery").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("executeQuery")).on(callable))
                    .method(named("execute").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("execute")).on(callable))
                    .method(named("getResultSet").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getResultSet")).on(callable))
                    .method(named("getUpdateCount").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getUpdateCount")).on(callable))
                    .method(named("getMoreResults").and(takesNoArguments()))
                    .intercept(MethodCall.invoke(PreparedStatementQueryHandler.class.getMethod("getMoreResults")).on(callable))
                    .make()) {
                return unloaded.load(StatementFactory.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                        .getLoaded()
                        .getDeclaredConstructor()
                        .newInstance();
            }
        } catch (Exception e) {
            throw new SQLException("Failed to create mock CallableStatement", e);
        }
    }
}
