package io.github.rroyoo.mockjdbc.mock.statement;

import io.github.rroyoo.mockjdbc.mock.driver.MockConfig;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

final class StatementQueryHandler {

    private final StatementLifecycleHandler lifecycle;
    private final StatementExecutionStateHandler executionState;
    private final GrpcMockQueryClient client;

    StatementQueryHandler(MockConfig mockConfig, StatementLifecycleHandler lifecycle, StatementExecutionStateHandler executionState) {
        this.lifecycle = lifecycle;
        this.executionState = executionState;
        this.client = new GrpcMockQueryClient(mockConfig);
    }

    public ResultSet executeQuery(String sql) throws SQLException {
        lifecycle.assertOpen();
        var resultSet = ResultSetFactory.create(client.findResultSet(sql, List.of()));
        executionState.storeResultSet(resultSet);
        return resultSet;
    }

    public boolean execute(String sql) throws SQLException {
        executeQuery(sql);
        return true;
    }

    public int executeUpdate(String sql) throws SQLException {
        lifecycle.assertOpen();
        var resultSet = client.findResultSet(sql, List.of());
        var count = resultSet.getRowsCount();
        executionState.storeUpdateCount(count);
        return count;
    }

    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return executeUpdate(sql);
    }

    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return executeUpdate(sql);
    }

    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return executeUpdate(sql);
    }

    public long executeLargeUpdate(String sql) throws SQLException {
        lifecycle.assertOpen();
        var resultSet = client.findResultSet(sql, List.of());
        var count = (long) resultSet.getRowsCount();
        executionState.storeLargeUpdateCount(count);
        return count;
    }

    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return executeLargeUpdate(sql);
    }

    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return executeLargeUpdate(sql);
    }

    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        return executeLargeUpdate(sql);
    }

    public ResultSet getResultSet() throws SQLException {
        lifecycle.assertOpen();
        return executionState.getResultSet();
    }

    public int getUpdateCount() throws SQLException {
        lifecycle.assertOpen();
        return executionState.getUpdateCount();
    }

    public long getLargeUpdateCount() throws SQLException {
        lifecycle.assertOpen();
        return executionState.getLargeUpdateCount();
    }

    public boolean getMoreResults() throws SQLException {
        lifecycle.assertOpen();
        return executionState.getMoreResults();
    }

    public boolean getMoreResults(int current) throws SQLException {
        lifecycle.assertOpen();
        return executionState.getMoreResults(current);
    }

    public void closeOnCompletion() throws SQLException {
        lifecycle.assertOpen();
        executionState.closeOnCompletion();
    }

    public boolean isCloseOnCompletion() throws SQLException {
        lifecycle.assertOpen();
        return executionState.isCloseOnCompletion();
    }
}
