spring:
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    url: jdbc:mock://${MOCKJDBC_GRPC_HOST:localhost}:${MOCKJDBC_GRPC_PORT:8088}
    driver-class-name: io.github.rroyoo.mockjdbc.mock.driver.MockDriver
  sql:
    init:
      mode: never
